# place this file in $HOME/.kube/config to load custom config cluyster
apiVersion: v1
kind: Config

preference: {}

clusters:
- name: dev
  cluster:
    certificate-authority: ca.crt # with file path
    server: https://172.17.0.51:6443 # server ip 
users:
- name: admin
  # can load certifactes for user
- name: dev1
- name: dev2

contexts:
- name: dev1@dev
  context:
    cluster: dev
    user: dev1
  namespace: dev
# user+cluster name concat this user can only access this cluster
- context:
   cluster: prod
   user: dev2
  name: dev2-dev # this user can only access this cluster
# admin user has comple access on all clusters 
- context:
   cluster: dev
   user: admin
  name: admin-dev
- context:
   cluster: prod
   user: admin
  name: admin-prod 
# can add client certificate data and client certificate key data too so user is pre-authorised to access cluster