apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-Deployment
  labels:
    name: nginx-demo 
    tier: type-1
spec:
  replicaset: 1
  selector:
    matchLabels:
      name: nginx-demo
  template:
    metadata:
      labels:
        app: ngginx-demo
    spec:
      containers:
        - name: nginx-pod
          image: nginx:alpine-18
