apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    tier: dev
  namespace: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    priorityClassName: high-priority
    ports:
    - containerPort: 8080
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30 rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
    resources:
      limits:
        cpu: "1000m"
        memory: "256Mi"
      requests:
        cpu: "50m"
        memory: "126Mi"