apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon
  labels:
    app: nginx
    tier: daemon
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        tier: daemon
    spec:
      tolerations:
      - key: "hw"
        operator: "Equal"
        value: "hp"
        effect: "NoSchedule"
      - key: "hw"
        operator: "Equal"
        value: "lp"
        effect: "PreferNoSchedule"
      containers:
      - name: nginx-daemon-container
        imagePullPolicy: IfNotPresent
        image: nginx:alpine
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "126Mi"