apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
  labels:
    app: nginx
    tier: front-end
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: Exists
            values: 
            - high-performance
  nodeSelector:
    name: node01
  containers:
  - name: nginx-container
    image: nginx:1.25
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"