apiVersion: v1
kind: Pod
metadata:
  name: node-aff
  labels:
    app: nginx
    tier: front-end
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "tanited"
            operator: "In"
            values: 
            - "yes"
  nodeSelector:
    name: node02
  containers:
  - name: nginx-container
    image: nginx:1.25
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"