apiVersion: v1
kind: Pod
metadata:
  name: tolarant
  labels:
    app: nginx
    tier: front-end
  namespace: dev
spec:
  affinity: # with node affinity pods are only directed towards this node
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "tainted"
                operator: "In"
                values:
                - "yes"
    # any pod without this toleration wont be scheduled on a node with taint of hardware=high-performance:NoSchedule effect
  # meaning only high perfomance pods should be scheduled here
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "hp"
    effect: "NoSchedule"
  priorityClassName: high-priority
  containers:
  - name: nginx-container
    image: nginx:1.25
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"