apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
  labels:
    app: nginx
    tier: front-end
  namespace: default
spec:
  # any pod without this toleration wont be scheduled on a node with taint of hardware=high-performance:NoSchedule effect
  # meaning only high perfomance pods should be scheduled here
  tolerations:
  - key: hardware
    operator: Equals
    value: high-performance
    effect: NoSchedule
  nodeSelector:
    name: node01
  containers:
  - name: nginx-container
    image: nginx:1.25
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"