apiVersion: autoscaling/v2
kind: HorizontalPodAutoScaler
metadata:
  name: nginx-depl-hpa
  labels:
    app: nginx
    tier: front-end
  namespace: edfault
spec:
  scalrTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-depl
      labels:
        app: nginx
        tier: front-end
    minReplicas: 1
    maxReplicas: 100
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50