ARG NODE_VERSION=18-alpine

FROM node:${NODE_VERSION} AS base

WORKDIR /app

COPY package*.json ./


FROM base AS builder

RUN npm ci

COPY . .

RUN npm build

FROM base AS prod-deps

RUN npm ci --only-production

FROM node:${NODE_VERSION} AS runner

ENV NODE_ENV=production

WORKDIR /app

COPY --from=builder /app/dist ./dist

COPY --from=prod-deps /app/node_modules /node_modules

COPY package*.json ./

EXPOSE 3000

CMD ["node" , "dist/server.js"]