apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-depl
  labels:
    app: nginx
    tier: front-end
  namespace: dev
spec:
  selector:
    matchLabels:
      app: nginx
      tier: front-end
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        tier: front-end
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts: # mount volumes on container
        - name: token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
        - name: db-connector
          mountPath: /var/app/db-connector
          readOnly: true
        - name: db-password
          mountPath: /var/app/db-password
          readOnly: true
        env: # this is also a version of how to inject env value directly into pod
        - name: DB_USR
          valueFrom:
            configMapKeyRef:
              name: db_env # configmap name
              key: db-user # configmap key ion data
        - name: DB_PSWD
          valueFrom:
            secretKeyRef:
              name: db_pswd # secrets file name
              key: psswd # secrets data key
      serviceAccountName: aws-service-account
      automountServiceAccountToken: false
      tolerations:
      - key: "vm"
        operator: "Equal"
        value: "dev"
        effect: "NoSchedule"
      - key: "vm"
        operator: "Equal"
        value: "stage"
        effect: "PreferNoSchedule"
      volumes: # define volume name at pod level
      - name: token
        projected: # for service account types
          sources:
          - serviceAccountToekn:
            name: token
          - configMap:
            name: db-connector # use the configmap with same name 
          - secret:
            name: db-password # use secret with same name