apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-service-account
  # annotations:
  #   kubernetes.io/enforce-mountable-secrets: "false"
automountServiceAccountToken: false # also mention in pod that uses this sa, and mopunt /var/run/secrets/kubernetes.io/serviceaccount vol on pod volume mounts with this path, so pods can pull token when used.
