kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster-local
nodes:
# -----------------------------------------------------------------------------
# Control Plane Node (Master)
# -----------------------------------------------------------------------------
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080 # Bypasses host port 80 conflict
    protocol: TCP
  - containerPort: 443
    hostPort: 8443 # Bypasses host port 443 conflict
    protocol: TCP

# -----------------------------------------------------------------------------
# Data Plane Nodes (Workers)
# -----------------------------------------------------------------------------
- role: worker
- role: worker
- role: worker